server:
    port: 8080
---
spring:
  profiles:
    active: local
---
spring:
    profiles:
      - local 
    datasource:
        driver-class-name: org.postgresql.Driver
        password: postgres
        platform: postgres
        url: jdbc:postgresql://localhost:5432/lesa
        username: postgres
    jpa:
        database: POSTGRESQL
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
